import { ETagNames } from "./enums";
import { ItemType } from "./types";

export const initializePageData = {
	advancedOptions: false,
	displayNumber: 4,
	augments: [],
	selectedAugments: {
		panel1: null,
		panel2: null,
		panel3: null,
		panel4: null,
		panel5: null,
		panel6: null,
	},
	suggestedItems: {
		panel1: null,
		panel2: null,
		panel3: null,
		panel4: null,
		panel5: null,
		panel6: null,
		itemSet: new Set<ItemType>(),
	},
	readOnlySuggItems: {
		panel1: null,
		panel2: null,
		panel3: null,
		panel4: null,
		panel5: null,
		panel6: null,
		itemSet: new Set<ItemType>(),
	},
	showPrismatics: true,
};

export const advancedOptionChoicesInitializer = {
	stats: {
		[ETagNames.AbilityHaste]: false,
		[ETagNames.AD]: false,
		[ETagNames.AdaptiveForce]: false,
		[ETagNames.AP]: false,
		[ETagNames.Armour]: false,
		[ETagNames.ArmourPen]: false,
		[ETagNames.ArmourShred]: false,
		[ETagNames.AttackSpeed]: false,
		[ETagNames.Crit]: false,
		[ETagNames.CritDamage]: false,
		[ETagNames.HealAndShieldPower]: false,
		[ETagNames.Health]: false,
		[ETagNames.HealthRegen]: false,
		[ETagNames.Lethality]: false,
		[ETagNames.Lifesteal]: false,
		[ETagNames.MagicPen]: false,
		[ETagNames.MagicResist]: false,
		[ETagNames.MagicResistShred]: false,
		[ETagNames.Mana]: false,
		[ETagNames.ManaRegen]: false,
		[ETagNames.MoveSpeed]: false,
		[ETagNames.Omnivamp]: false,
		[ETagNames.RangeIncrease]: false,
		[ETagNames.SummonerSpellCooldown]: false,
		[ETagNames.Tenacity]: false,
	},
	scalings: {
		[ETagNames.ArmourScaling]: false,
		[ETagNames.CritScaling]: false,
		[ETagNames.MagicResistScaling]: false,
		[ETagNames.ManaScaling]: false,
		[ETagNames.MaxHealthScaling]: false,
		[ETagNames.MissingHealthScaling]: false,
	},
	effects: {
		[ETagNames.AOE]: false,
		[ETagNames.AutoReset]: false,
		[ETagNames.Bleed]: false,
		[ETagNames.Block]: false,
		[ETagNames.Burn]: false,
		[ETagNames.CooldownReduction]: false,
		[ETagNames.CurrentHealthDamage]: false,
		[ETagNames.DamageSteroid]: false,
		[ETagNames.Energized]: false,
		[ETagNames.EnhancedAutoAttack]: false,
		[ETagNames.Execute]: false,
		[ETagNames.Grievous]: false,
		[ETagNames.Heal]: false,
		[ETagNames.Immobilize]: false,
		[ETagNames.ImmobilizeEnhancer]: false,
		[ETagNames.MaxHealthDamage]: false,
		[ETagNames.MissingHealthDamage]: false,
		[ETagNames.Movement]: false,
		[ETagNames.OnTakedownEffect]: false,
		[ETagNames.OnHit]: false,
		[ETagNames.Projectile]: false,
		[ETagNames.Shield]: false,
		[ETagNames.Slow]: false,
		[ETagNames.UltimateScaling]: false,
	},
	role: {
		[ETagNames.ADC]: false,
		[ETagNames.Assassin]: false,
		[ETagNames.Bruiser]: false,
		[ETagNames.Hybrid]: false,
		[ETagNames.Mage]: false,
		[ETagNames.Sniper]: false,
		[ETagNames.Support]: false,
		[ETagNames.Tank]: false,
	},
	playstyle: {
		[ETagNames.Aggressive]: false,
		[ETagNames.AutoAttacking]: false,
		[ETagNames.AutoWeaving]: false,
		[ETagNames.Burst]: false,
		[ETagNames.Defensive]: false,
		[ETagNames.Kiting]: false,
		[ETagNames.OnlyChild]: false,
		[ETagNames.PositioningPattern]: false,
		[ETagNames.SpellHeavy]: false,
		[ETagNames.SpellWeaving]: false,
		[ETagNames.Stacking]: false,
		[ETagNames.Sticky]: false,
	},
	misc: {
		[ETagNames.Active]: false,
		[ETagNames.Targeted]: false,
		[ETagNames.TrueDamage]: false,
		[ETagNames.Untargetability]: false,
		[ETagNames.LongRange]: false,
		[ETagNames.Twinning]: false,
	},
};

export const ChampPageInitilizer = {
	saveMessage: null,
	currentBuild: { name: "", augments: [], items: [], build_id: 0 },
	allBuilds: [],
	pageLoading: true,
	isEditing: false,
	title: "",
	selectedAugs: [],
};
